//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatOutdoors.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public System.Guid OrderDetailID { get; set; }
        public System.Guid OrderID { get; set; }
        public System.Guid ProductID { get; set; }
        public int Quantity { get; set; }
        public decimal DiscountedUnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<bool> GiftPacking { get; set; }
        public System.Guid AddressID { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
