//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatOutdoors.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Return()
        {
            this.ReturnDetails = new HashSet<ReturnDetail>();
        }
    
        public System.Guid ReturnID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public string ChannelOfReturn { get; set; }
        public decimal ReturnAmount { get; set; }
        public System.DateTime ReturnDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnDetail> ReturnDetails { get; set; }
    }
}
