//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatOutdoors.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnDetail
    {
        public System.Guid ReturnDetailID { get; set; }
        public Nullable<System.Guid> ReturnID { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public int Quantity { get; set; }
        public string ReasonOfReturn { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<System.Guid> AddressID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Product Product { get; set; }
        public virtual Return Return { get; set; }
    }
}
